services:
  influxdb:
    image: docker.io/library/influxdb:1.11
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: changeme
    volumes:
      - /home/pi/monitoring/influxdb/var_lib_influxdb:/var/lib/influxdb
      - /home/pi/monitoring/influxdb/etc_influxdb:/etc/influxdb

  grafana:
    image: docker.io/grafana/grafana-enterprise:latest
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /home/pi/monitoring/grafana/var_lib_grafana:/var/lib/grafana:rw
      - /home/pi/monitoring/grafana/var_log_grafana:/var/log/grafana:rw
      - /home/pi/monitoring/grafana/etc_grafana:/etc/grafana:rw

  mqtt2influx:
    image: ghcr.io/edjopato/mqtt2influxdb:2
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      MQTT_BROKER: mqtt-broker
      MQTT_PORT: 1883
      MQTT_TOPIC: "#"
      INFLUX_HOST: http://influxdb:8086/
      INFLUX_DATABASE: mqtt
      INFLUX_TOKEN: changeme

  mqtt-broker:
    image: docker.io/library/eclipse-mosquitto:2
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/pi/monitoring/mqtt/conf:/mosquitto/conf
      - /home/pi/monitoring/mqtt/data:/mosquitto/data
      - /home/pi/monitoring/mqtt/log:/mosquitto/log
      - /home/pi/monitoring/mqtt/conf/mosquitto.conf:/mosquitto/conf/mosquitto.conf
      # - /home/pi/monitoring/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
